import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { NAMES } from './names.mjs';

if (NAMES.length !== 99) {
  console.error(`Expected 99 names, got ${NAMES.length}`);
  process.exit(1);
}

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
const pad = (n) => String(n).padStart(3, '0');

const entries = NAMES.map(([arabic, trn, meaning, trnBn, meaningBn, verse], i) => {
  const n = i + 1;
  // A verse where the name is said of Allah, or else the narration that lists it.
  const [source, ref] = verse ? ['Quran', verse] : ['At-Tirmidhi', '3507'];
  return `  {
    step: 3,
    id: 'asma_${pad(n)}',
    title: { en: '${esc(trn)}', bn: '${esc(trnBn)}' },
    arabic: '${esc(arabic)}',
    trn: { en: '${esc(trn)}', bn: '${esc(trnBn)}' },
    meaning: { en: '${esc(meaning)}', bn: '${esc(meaningBn)}' },
    cat: ['names'],
    tags: ['asmaul-husna', 'names', '${esc(trn.toLowerCase())}'],
    target: 0,
    source: '${source}',
    ref: '${ref}'
  }`;
});

const file = `import { DhikrItem } from '../constants';

/**
 * The ninety-nine names, in the order of the narration in at-Tirmidhi (3507).
 *
 * On provenance: the Quranic instruction is unambiguous — "To Allah belong the
 * most beautiful names, so call upon Him by them" (7:180) — and every name here
 * is attested. The specific enumeration of exactly ninety-nine, however, comes
 * from a narration many scholars read as a narrator's list rather than the
 * Prophet's ﷺ own words, and other lists differ slightly. That caveat, and
 * 7:180 itself, sit once on the category rather than on every name.
 *
 * Each name cites where it is found: a verse in which the name itself is said
 * of Allah, or — for the names the Qur'an has only as a verb (al-Qabid,
 * al-Mu'izz, al-Mumeet) or not at all — the narration that lists it. The same
 * 7:180 printed ninety-nine times said nothing about any one of them. The
 * verses are chosen in scripts/names.mjs and checked against the Qur'an text
 * by scripts/verify-name-verses.mjs.
 *
 * Bangla names and meanings are a reviewed human translation, not machine
 * output — the transliterations in particular are a pronunciation aid, and
 * Bengali script cannot represent every Arabic letter or point of articulation
 * exactly. A single gloss in either language cannot carry a divine name's full
 * sense; these are a way in, not a definition.
 *
 * target: 0 on every name. With a target of 1 the completion branch in
 * handleIncrement would fire confetti, the success chord and a five-pulse
 * vibration ninety-nine times in a single round. The cycle item below is what
 * marks a completed round instead.
 *
 * Generated by scripts/build-names.mjs — edit that, not this.
 */
export const ASMA_DATA: DhikrItem[] = [
${entries.join(',\n')}
];

/**
 * A single item standing for one completed round of all ninety-nine.
 *
 * It lives in DHIKR_DATA but not in the browsable set, so the Record can name
 * it properly while it never appears as a stray row in a du'a list. Counting
 * ninety-nine separate ids would bury every other dhikr in "Most recited".
 */
export const ASMA_CYCLE_ITEM: DhikrItem = {
  step: 3,
  id: 'asma_cycle',
  title: { en: 'Asma ul Husna', bn: 'আসমাউল হুসনা' },
  arabic: '',
  meaning: { en: 'One complete round of the names of Allah.', bn: 'আল্লাহর নামসমূহের একটি পূর্ণ চক্র।' },
  cat: [],
  target: 1,
  source: 'Quran',
  ref: '7:180'
};

/** True for the names themselves, not the cycle marker. */
export const isAsmaId = (id: string): boolean => id.startsWith('asma_') && id !== 'asma_cycle';
`;

writeFileSync(
  join(dirname(fileURLToPath(import.meta.url)), '../src/data/asmaulHusna.ts'),
  file
);
console.log(`wrote ${NAMES.length} names`);
