/**
 * The ninety-nine names, in the order of the narration in at-Tirmidhi (3507).
 *
 * [arabic, transliteration, meaning, transliteration (bn), meaning (bn), verse]
 *
 * `verse` is a place in the Qur'an where the name itself is said of Allah —
 * definite or indefinite, with an attached particle allowed (وَ, لَ, بِ), but
 * never a verb from the same root. "يُحْيِي" is not "ٱلْمُحْيِي"; "لَمُحْيِي"
 * in 30:50 is. Where no such verse exists the name is cited to the narration
 * it is listed in, and `verse` is null — a derived name is not given a verse
 * that merely shares its root.
 *
 * Each verse is checked by scripts/verify-name-verses.mjs against the Qur'an
 * text: the name has to be in the verse. That the verse speaks of Allah is a
 * reader's judgement, and was made by one; re-check it when changing a row.
 */
export const NAMES = [
  ['ٱلرَّحْمَٰنُ', 'Ar-Rahman', 'The Most Compassionate', 'আর-রহমান', 'পরম করুণাময়', '59:22'],
  ['ٱلرَّحِيمُ', 'Ar-Raheem', 'The Most Merciful', 'আর-রহীম', 'পরম দয়ালু', '59:22'],
  ['ٱلْمَلِكُ', 'Al-Malik', 'The King, the Sovereign', 'আল-মালিক', 'সর্বময় রাজা ও অধিপতি', '59:23'],
  ['ٱلْقُدُّوسُ', 'Al-Quddus', 'The Most Holy', 'আল-কুদ্দূস', 'পরম পবিত্র', '59:23'],
  ['ٱلسَّلَامُ', 'As-Salam', 'The Source of Peace', 'আস-সালাম', 'শান্তি ও নিরাপত্তার উৎস', '59:23'],
  ['ٱلْمُؤْمِنُ', "Al-Mu'min", 'The Giver of Security', 'আল-মু’মিন', 'নিরাপত্তা ও আশ্বাস দানকারী', '59:23'],
  ['ٱلْمُهَيْمِنُ', 'Al-Muhaymin', 'The Guardian over all', 'আল-মুহাইমিন', 'সর্বতত্ত্বাবধায়ক ও রক্ষক', '59:23'],
  ['ٱلْعَزِيزُ', 'Al-Azeez', 'The Almighty', 'আল-আযীয', 'পরাক্রমশালী', '59:23'],
  ['ٱلْجَبَّارُ', 'Al-Jabbar', 'The Compeller, the Restorer', 'আল-জাব্বার', 'মহাপরাক্রমশালী নিয়ন্ত্রক ও সংশোধনকারী', '59:23'],
  ['ٱلْمُتَكَبِّرُ', 'Al-Mutakabbir', 'The Supreme in Greatness', 'আল-মুতাকাব্বির', 'মহিমা ও শ্রেষ্ঠত্বে সর্বোচ্চ', '59:23'],
  ['ٱلْخَالِقُ', 'Al-Khaliq', 'The Creator', 'আল-খালিক', 'সৃষ্টিকর্তা', '59:24'],
  ['ٱلْبَارِئُ', "Al-Bari'", 'The Originator', 'আল-বারি’', 'অনস্তিত্ব থেকে সৃষ্টির সূচনাকারী', '59:24'],
  ['ٱلْمُصَوِّرُ', 'Al-Musawwir', 'The Fashioner of forms', 'আল-মুসাওয়ির', 'আকৃতি ও রূপদানকারী', '59:24'],
  ['ٱلْغَفَّارُ', 'Al-Ghaffar', 'The Ever-Forgiving', 'আল-গাফফার', 'বারবার ক্ষমাকারী', '38:66'],
  ['ٱلْقَهَّارُ', 'Al-Qahhar', 'The All-Prevailing', 'আল-কাহহার', 'সর্বজয়ী ও অপ্রতিরোধ্য', '13:16'],
  ['ٱلْوَهَّابُ', 'Al-Wahhab', 'The Bestower of gifts', 'আল-ওয়াহহাব', 'অঢেল দানকারী', '3:8'],
  ['ٱلرَّزَّاقُ', 'Ar-Razzaq', 'The Provider', 'আর-রাযযাক', 'রিযিকদাতা', '51:58'],
  ['ٱلْفَتَّاحُ', 'Al-Fattah', 'The Opener, the Judge', 'আল-ফাত্তাহ', 'উন্মোচনকারী ও ফয়সালাকারী', '34:26'],
  ['ٱلْعَلِيمُ', 'Al-Aleem', 'The All-Knowing', 'আল-আলীম', 'সর্বজ্ঞ', '2:32'],
  ['ٱلْقَابِضُ', 'Al-Qabid', 'The Withholder', 'আল-কাবিদ', 'সংকুচিতকারী ও রোধকারী', null],
  ['ٱلْبَاسِطُ', 'Al-Basit', 'The Extender', 'আল-বাসিত', 'প্রসারিতকারী', null],
  ['ٱلْخَافِضُ', 'Al-Khafid', 'The Abaser', 'আল-খাফিদ', 'অবনতকারী', null],
  ['ٱلرَّافِعُ', "Ar-Rafi'", 'The Exalter', 'আর-রাফি’', 'মর্যাদা উন্নীতকারী', null],
  ['ٱلْمُعِزُّ', "Al-Mu'izz", 'The Giver of honour', 'আল-মু’ইযয', 'সম্মানদাতা', null],
  ['ٱلْمُذِلُّ', 'Al-Mudhill', 'The Giver of dishonour', 'আল-মুযিল্ল', 'অপমান ও অবনতি দানকারী', null],
  ['ٱلسَّمِيعُ', "As-Samee'", 'The All-Hearing', 'আস-সামী’', 'সর্বশ্রোতা', '42:11'],
  ['ٱلْبَصِيرُ', 'Al-Baseer', 'The All-Seeing', 'আল-বাসীর', 'সর্বদ্রষ্টা', '42:11'],
  ['ٱلْحَكَمُ', 'Al-Hakam', 'The Judge', 'আল-হাকাম', 'চূড়ান্ত বিচারক', null],
  ['ٱلْعَدْلُ', 'Al-Adl', 'The Utterly Just', 'আল-আদল', 'পরিপূর্ণ ন্যায়বিচারকারী', null],
  ['ٱللَّطِيفُ', 'Al-Lateef', 'The Subtle, the Gentle', 'আল-লতীফ', 'অতি সূক্ষ্মদর্শী ও কোমল', '67:14'],
  ['ٱلْخَبِيرُ', 'Al-Khabeer', 'The All-Aware', 'আল-খবীর', 'সর্ববিষয়ে অবগত', '67:14'],
  ['ٱلْحَلِيمُ', 'Al-Haleem', 'The Forbearing', 'আল-হালীম', 'পরম সহনশীল', '2:225'],
  ['ٱلْعَظِيمُ', 'Al-Azeem', 'The Magnificent', 'আল-আযীম', 'মহামহিমান্বিত', '2:255'],
  ['ٱلْغَفُورُ', 'Al-Ghafoor', 'The Much-Forgiving', 'আল-গফূর', 'অত্যন্ত ক্ষমাশীল', '10:107'],
  ['ٱلشَّكُورُ', 'Ash-Shakoor', 'The Most Appreciative', 'আশ-শাকূর', 'বান্দার সৎকর্মের কদরদানকারী ও অধিক প্রতিদানদাতা', '64:17'],
  ['ٱلْعَلِيُّ', 'Al-Aliyy', 'The Most High', 'আল-আলিয়্য', 'সর্বোচ্চ', '2:255'],
  ['ٱلْكَبِيرُ', 'Al-Kabeer', 'The Most Great', 'আল-কবীর', 'সুমহান', '13:9'],
  ['ٱلْحَفِيظُ', 'Al-Hafeez', 'The Preserver', 'আল-হাফীয', 'সংরক্ষণকারী', '11:57'],
  ['ٱلْمُقِيتُ', 'Al-Muqeet', 'The Sustainer', 'আল-মুকীত', 'জীবিকা ও শক্তির যোগানদাতা', '4:85'],
  ['ٱلْحَسِيبُ', 'Al-Haseeb', 'The Reckoner', 'আল-হাসীব', 'হিসাবগ্রহণকারী', '4:86'],
  ['ٱلْجَلِيلُ', 'Al-Jaleel', 'The Majestic', 'আল-জালীল', 'মহামহিম', null],
  ['ٱلْكَرِيمُ', 'Al-Kareem', 'The Most Generous', 'আল-করীম', 'পরম উদার', '82:6'],
  ['ٱلرَّقِيبُ', 'Ar-Raqeeb', 'The Watchful', 'আর-রাকীব', 'সদা পর্যবেক্ষণকারী', '4:1'],
  ['ٱلْمُجِيبُ', 'Al-Mujeeb', 'The Responsive to prayer', 'আল-মুজীব', 'দোয়া কবুলকারী', '11:61'],
  ['ٱلْوَاسِعُ', "Al-Wasi'", 'The All-Encompassing', 'আল-ওয়াসি’', 'সর্বব্যাপী ও সর্বসমৃদ্ধ', '2:115'],
  ['ٱلْحَكِيمُ', 'Al-Hakeem', 'The All-Wise', 'আল-হাকীম', 'পরম প্রজ্ঞাময়', '2:32'],
  ['ٱلْوَدُودُ', 'Al-Wadood', 'The Most Loving', 'আল-ওয়াদূদ', 'পরম স্নেহশীল', '85:14'],
  ['ٱلْمَجِيدُ', 'Al-Majeed', 'The Most Glorious', 'আল-মাজীদ', 'পরম গৌরবময়', '11:73'],
  ['ٱلْبَاعِثُ', "Al-Ba'ith", 'The Raiser of the dead', 'আল-বা’ইস', 'পুনরুত্থানকারী', null],
  ['ٱلشَّهِيدُ', 'Ash-Shaheed', 'The Witness over all', 'আশ-শাহীদ', 'সর্বসাক্ষী', '22:17'],
  ['ٱلْحَقُّ', 'Al-Haqq', 'The Absolute Truth', 'আল-হাক্ক', 'পরম সত্য', '22:6'],
  ['ٱلْوَكِيلُ', 'Al-Wakeel', 'The Trustee, the Disposer of affairs', 'আল-ওয়াকীল', 'কর্মবিধায়ক ও নির্ভরযোগ্য অভিভাবক', '3:173'],
  ['ٱلْقَوِيُّ', 'Al-Qawiyy', 'The All-Strong', 'আল-কাওয়িয়্য', 'পরম শক্তিধর', '42:19'],
  ['ٱلْمَتِينُ', 'Al-Mateen', 'The Firm, the Steadfast', 'আল-মাতীন', 'সুদৃঢ় ও অটল', '51:58'],
  ['ٱلْوَلِيُّ', 'Al-Waliyy', 'The Protecting Friend', 'আল-ওয়ালিয়্য', 'অভিভাবক ও সাহায্যকারী', '42:28'],
  ['ٱلْحَمِيدُ', 'Al-Hameed', 'The Praiseworthy', 'আল-হামীদ', 'সর্বপ্রশংসিত', '31:26'],
  ['ٱلْمُحْصِي', 'Al-Muhsee', 'The All-Enumerating', 'আল-মুহসী', 'সবকিছুর হিসাব ও সংখ্যা ধারণকারী', null],
  ['ٱلْمُبْدِئُ', "Al-Mubdi'", 'The Originator of creation', 'আল-মুবদি’', 'সৃষ্টির প্রথম সূচনাকারী', null],
  ['ٱلْمُعِيدُ', "Al-Mu'eed", 'The Restorer of life', 'আল-মু’ঈদ', 'পুনরায় ফিরিয়ে আনেন যিনি', null],
  ['ٱلْمُحْيِي', 'Al-Muhyee', 'The Giver of life', 'আল-মুহয়ী', 'জীবনদাতা', '30:50'],
  ['ٱلْمُمِيتُ', 'Al-Mumeet', 'The Bringer of death', 'আল-মুমীত', 'মৃত্যুদাতা', null],
  ['ٱلْحَيُّ', 'Al-Hayy', 'The Ever-Living', 'আল-হাইয়্য', 'চিরঞ্জীব', '2:255'],
  ['ٱلْقَيُّومُ', 'Al-Qayyoom', 'The Sustainer of all', 'আল-কাইয়্যূম', 'স্বয়ংস্থিত ও সবকিছুর ধারক', '2:255'],
  ['ٱلْوَاجِدُ', 'Al-Wajid', 'The Finder, the Self-Sufficient', 'আল-ওয়াজিদ', 'সবকিছুর প্রাপ্তিকারী ও অভাবমুক্ত', null],
  ['ٱلْمَاجِدُ', 'Al-Majid', 'The Noble, the Glorious', 'আল-মাজিদ', 'মহামর্যাদাবান ও গৌরবময়', null],
  ['ٱلْوَاحِدُ', 'Al-Wahid', 'The One', 'আল-ওয়াহিদ', 'এক ও অদ্বিতীয়', '13:16'],
  ['ٱلْأَحَدُ', 'Al-Ahad', 'The Indivisible, the Unique', 'আল-আহাদ', 'একক ও অতুলনীয়', '112:1'],
  ['ٱلصَّمَدُ', 'As-Samad', 'The Eternal Refuge', 'আস-সামাদ', 'সকলের আশ্রয় ও অমুখাপেক্ষী', '112:2'],
  ['ٱلْقَادِرُ', 'Al-Qadir', 'The All-Powerful', 'আল-কাদির', 'সর্বক্ষমতাবান', '6:65'],
  ['ٱلْمُقْتَدِرُ', 'Al-Muqtadir', 'The Omnipotent', 'আল-মুকতাদির', 'সর্বময় ক্ষমতার অধিকারী', '54:55'],
  ['ٱلْمُقَدِّمُ', 'Al-Muqaddim', 'The Expediter', 'আল-মুকাদ্দিম', 'অগ্রসরকারী', null],
  ['ٱلْمُؤَخِّرُ', "Al-Mu'akhkhir", 'The Delayer', 'আল-মু’আখখির', 'বিলম্বকারী', null],
  ['ٱلْأَوَّلُ', 'Al-Awwal', 'The First, without beginning', 'আল-আউয়াল', 'সর্বপ্রথম, যার কোনো শুরু নেই', '57:3'],
  ['ٱلْآخِرُ', 'Al-Akhir', 'The Last, without end', 'আল-আখির', 'সর্বশেষ, যার কোনো শেষ নেই', '57:3'],
  ['ٱلظَّاهِرُ', 'Az-Zahir', 'The Manifest', 'আয-যাহির', 'প্রকাশ্য ও সুস্পষ্ট', '57:3'],
  ['ٱلْبَاطِنُ', 'Al-Batin', 'The Hidden', 'আল-বাতিন', 'গুপ্ত ও অন্তর্নিহিত', '57:3'],
  ['ٱلْوَالِي', 'Al-Walee', 'The Governor of all', 'আল-ওয়ালী', 'সর্বময় শাসক', null],
  ['ٱلْمُتَعَالِي', "Al-Muta'ali", 'The Most Exalted', 'আল-মুতা’আলী', 'সর্বোচ্চ মর্যাদার অধিকারী', '13:9'],
  ['ٱلْبَرُّ', 'Al-Barr', 'The Source of all goodness', 'আল-বার্র', 'পরম কল্যাণকারী', '52:28'],
  ['ٱلتَّوَّابُ', 'At-Tawwab', 'The Ever-Accepting of repentance', 'আত-তাওয়াব', 'তওবা কবুলকারী', '2:37'],
  ['ٱلْمُنْتَقِمُ', 'Al-Muntaqim', 'The Avenger', 'আল-মুনতাকিম', 'অপরাধের ন্যায়সংগত প্রতিফলদাতা', null],
  ['ٱلْعَفُوُّ', 'Al-Afuww', 'The Pardoner', 'আল-আফুউ', 'পরম ক্ষমাকারী', '4:43'],
  ['ٱلرَّءُوفُ', "Ar-Ra'oof", 'The Most Kind', 'আর-রউফ', 'পরম স্নেহশীল ও দয়ালু', '2:143'],
  ['مَالِكُ ٱلْمُلْكِ', 'Malik-ul-Mulk', 'Owner of all sovereignty', 'মালিকুল-মুলক', 'সমগ্র রাজত্বের মালিক', '3:26'],
  ['ذُو ٱلْجَلَالِ وَٱلْإِكْرَامِ', 'Dhul-Jalali wal-Ikram', 'Lord of Majesty and Generosity', 'যুল-জালালি ওয়াল-ইকরাম', 'মহিমা ও সম্মানের অধিকারী', '55:27'],
  ['ٱلْمُقْسِطُ', 'Al-Muqsit', 'The Equitable', 'আল-মুকসিত', 'ন্যায়সঙ্গত ও সুবিচারকারী', null],
  ['ٱلْجَامِعُ', "Al-Jami'", 'The Gatherer', 'আল-জামি’', 'সমবেতকারী', '3:9'],
  ['ٱلْغَنِيُّ', 'Al-Ghaniyy', 'The Self-Sufficient', 'আল-গনিয়্য', 'সম্পূর্ণ অভাবমুক্ত', '35:15'],
  ['ٱلْمُغْنِي', 'Al-Mughnee', 'The Enricher', 'আল-মুগনী', 'সমৃদ্ধিদাতা', null],
  ['ٱلْمَانِعُ', "Al-Mani'", 'The Withholder of harm', 'আল-মানি’', 'বাধাদানকারী ও প্রতিরোধকারী', null],
  ['ٱلضَّارُّ', 'Ad-Darr', 'The One who can cause harm', 'আদ-দার্র', 'যাঁর ইচ্ছা ও হিকমত অনুযায়ী ক্ষতি সংঘটিত হয়', null],
  ['ٱلنَّافِعُ', "An-Nafi'", 'The Bringer of benefit', 'আন-নাফি’', 'উপকারদাতা', null],
  ['ٱلنُّورُ', 'An-Noor', 'The Light', 'আন-নূর', 'আলো', '24:35'],
  ['ٱلْهَادِي', 'Al-Hadee', 'The Guide', 'আল-হাদী', 'পথপ্রদর্শক', '25:31'],
  ['ٱلْبَدِيعُ', "Al-Badee'", 'The Incomparable Originator', 'আল-বাদী’', 'অতুলনীয় সৃষ্টির উদ্ভাবক', '2:117'],
  ['ٱلْبَاقِي', 'Al-Baqee', 'The Everlasting', 'আল-বাকী', 'চিরস্থায়ী', null],
  ['ٱلْوَارِثُ', 'Al-Warith', 'The Inheritor of all', 'আল-ওয়ারিস', 'সকল কিছুর চূড়ান্ত উত্তরাধিকারী', null],
  ['ٱلرَّشِيدُ', 'Ar-Rasheed', 'The Guide to the right path', 'আর-রশীদ', 'সঠিক পথের দিশারি', null],
  ['ٱلصَّبُورُ', 'As-Saboor', 'The Most Patient', 'আস-সবূর', 'পরম ধৈর্যশীল', null],
];
