/**
 * The verse under each name: the Arabic, and two published translations.
 *
 * Arabic: Tanzil (simple). English: Sahih International. Bangla: Dr. Abu Bakr
 * Muhammad Zakaria (King Fahd Complex). The bismillah is taken off verse 1 and
 * Zakaria's footnote markers are removed; nothing else is changed. See
 * scripts/build-name-verses.mjs for why.
 *
 * `NAME_HIGHLIGHT` is where the name sits in its verse, as [first, last]
 * indexes into `arabic.split(' ')`.
 *
 * Generated by scripts/build-name-verses.mjs — edit that, not this.
 */
export interface NameVerse {
  arabic: string;
  meaning: { en: string; bn: string };
}

export const VERSE_TRANSLATORS = {
  en: 'Sahih International',
  bn: 'ড. আবু বকর মুহাম্মাদ যাকারিয়া'
};

export const NAME_VERSES: Record<string, NameVerse> = {
  "59:22": {
    "arabic": "هُوَ اللَّهُ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ ۖ عَالِمُ الْغَيْبِ وَالشَّهَادَةِ ۖ هُوَ الرَّحْمَٰنُ الرَّحِيمُ",
    "meaning": {
      "en": "He is Allah, other than whom there is no deity, Knower of the unseen and the witnessed. He is the Entirely Merciful, the Especially Merciful",
      "bn": "তিনিই আল্লাহ, তিনি ছাড়া কোনো সত্য ইলাহ নেই, তিনি গায়েব ও উপস্থিত বিষয়াদির জ্ঞানী; তিনি দয়াময়, পরম দয়ালু।"
    }
  },
  "59:23": {
    "arabic": "هُوَ اللَّهُ الَّذِي لَا إِلَٰهَ إِلَّا هُوَ الْمَلِكُ الْقُدُّوسُ السَّلَامُ الْمُؤْمِنُ الْمُهَيْمِنُ الْعَزِيزُ الْجَبَّارُ الْمُتَكَبِّرُ ۚ سُبْحَانَ اللَّهِ عَمَّا يُشْرِكُونَ",
    "meaning": {
      "en": "He is Allah, other than whom there is no deity, the Sovereign, the Pure, the Perfection, the Bestower of Faith, the Overseer, the Exalted in Might, the Compeller, the Superior. Exalted is Allah above whatever they associate with Him",
      "bn": "তিনি আল্লাহ্‌, তিনি ছাড়া কোনো সত্য ইলাহ নেই। তিনিই অধিপতি, মহাপবিত্র, ক্রটিমুক্ত, নিরাপত্তা বিধায়ক, রক্ষক, পরাক্রমশালী, প্রবল, অতীব মহিমান্বিত। তারা যা শরীক স্থির করে আল্লাহ্‌ তা হতে পবিত্র, মহান।"
    }
  },
  "59:24": {
    "arabic": "هُوَ اللَّهُ الْخَالِقُ الْبَارِئُ الْمُصَوِّرُ ۖ لَهُ الْأَسْمَاءُ الْحُسْنَىٰ ۚ يُسَبِّحُ لَهُ مَا فِي السَّمَاوَاتِ وَالْأَرْضِ ۖ وَهُوَ الْعَزِيزُ الْحَكِيمُ",
    "meaning": {
      "en": "He is Allah, the Creator, the Inventor, the Fashioner; to Him belong the best names. Whatever is in the heavens and earth is exalting Him. And He is the Exalted in Might, the Wise",
      "bn": "তিনিই আল্লাহ সৃজনকর্তা, উদ্ভাবন কর্তা, তাঁরই সকল উত্তম নাম। আসমানসমূহ ও যমীনে যা কিছু আছে, সবকিছুই তাঁর পবিত্রতা ও মহিমা ঘোষণা করে। তিনি পরক্রমশালী, প্রজ্ঞাময়।"
    }
  },
  "38:66": {
    "arabic": "رَبُّ السَّمَاوَاتِ وَالْأَرْضِ وَمَا بَيْنَهُمَا الْعَزِيزُ الْغَفَّارُ",
    "meaning": {
      "en": "Lord of the heavens and the earth and whatever is between them, the Exalted in Might, the Perpetual Forgiver",
      "bn": "যিনি আসমানসমূহ, যমীন ও তাদের মধ্যবর্তী সমস্ত কিছুর রব, প্রবল পরাক্রমশালী, মহাক্ষমাশীল।"
    }
  },
  "13:16": {
    "arabic": "قُلْ مَنْ رَبُّ السَّمَاوَاتِ وَالْأَرْضِ قُلِ اللَّهُ ۚ قُلْ أَفَاتَّخَذْتُمْ مِنْ دُونِهِ أَوْلِيَاءَ لَا يَمْلِكُونَ لِأَنْفُسِهِمْ نَفْعًا وَلَا ضَرًّا ۚ قُلْ هَلْ يَسْتَوِي الْأَعْمَىٰ وَالْبَصِيرُ أَمْ هَلْ تَسْتَوِي الظُّلُمَاتُ وَالنُّورُ ۗ أَمْ جَعَلُوا لِلَّهِ شُرَكَاءَ خَلَقُوا كَخَلْقِهِ فَتَشَابَهَ الْخَلْقُ عَلَيْهِمْ ۚ قُلِ اللَّهُ خَالِقُ كُلِّ شَيْءٍ وَهُوَ الْوَاحِدُ الْقَهَّارُ",
    "meaning": {
      "en": "Say, \"Who is Lord of the heavens and earth?\" Say, \"Allah.\" Say, \"Have you then taken besides Him allies not possessing [even] for themselves any benefit or any harm?\" Say, \"Is the blind equivalent to the seeing? Or is darkness equivalent to light? Or have they attributed to Allah partners who created like His creation so that the creation [of each] seemed similar to them?\" Say, \"Allah is the Creator of all things, and He is the One, the Prevailing",
      "bn": "বলুন, ‘কে আসমানসমূহ ও যমীনের রব?’ বলুন, ‘আল্লাহ্‌।’ বলুন, ‘তবে কি তোমরা অভিভাবকরূপে গ্রহণ করেছ আল্লাহর পরিবর্তে অন্যকে যারা নিজেদের লাভ বা ক্ষতি সাধনে সক্ষম নয়?’ বলুন, ‘অন্ধ ও চক্ষুষ্মান কি সমান হতে পারে? নাকি অন্ধকার ও আলো সমান হতে পারে?’ তবে কি তারা আল্লাহ্‌র এমন শরীক সৃষ্টি করেছে, যারা আল্লাহর সৃষ্টির মত সৃষ্টি করেছে, যে কারণে সৃষ্টি তাদের কাছে সদৃশ মনে হয়েছে? বলুন, ‘আল্লাহ্ সকল বস্তুর স্রষ্টা; আর তিনি এক, মহা প্রতাপশালী।’"
    }
  },
  "3:8": {
    "arabic": "رَبَّنَا لَا تُزِغْ قُلُوبَنَا بَعْدَ إِذْ هَدَيْتَنَا وَهَبْ لَنَا مِنْ لَدُنْكَ رَحْمَةً ۚ إِنَّكَ أَنْتَ الْوَهَّابُ",
    "meaning": {
      "en": "[Who say], \"Our Lord, let not our hearts deviate after You have guided us and grant us from Yourself mercy. Indeed, You are the Bestower",
      "bn": "‘হে আমাদের রব! সরল পথ দেয়ার পর আপনি আমাদের অন্তরসমূহকে সত্য লঙ্ঘনপ্রবণ করবেন না। আর আপনার কাছ থেকে আমাদেরকে করুণা দান করুন, নিশ্চয়ই আপনি মহাদাতা।’"
    }
  },
  "51:58": {
    "arabic": "إِنَّ اللَّهَ هُوَ الرَّزَّاقُ ذُو الْقُوَّةِ الْمَتِينُ",
    "meaning": {
      "en": "Indeed, it is Allah who is the [continual] Provider, the firm possessor of strength",
      "bn": "নিশ্চয় আল্লাহ, তিনিই তো রিযিকদাতা, প্রবল শক্তিধর, পরাক্রমশালী।"
    }
  },
  "34:26": {
    "arabic": "قُلْ يَجْمَعُ بَيْنَنَا رَبُّنَا ثُمَّ يَفْتَحُ بَيْنَنَا بِالْحَقِّ وَهُوَ الْفَتَّاحُ الْعَلِيمُ",
    "meaning": {
      "en": "Say, \"Our Lord will bring us together; then He will judge between us in truth. And He is the Knowing Judge",
      "bn": "বলুন, 'আমাদের রব আমাদের সকলকে একত্র করবেন, তারপর তিনি আমাদের মধ্যে সঠিকভাবে ফায়সালা করে দেবেন। আর তিনিই শ্রেষ্ঠ ফয়সালাকারী, সর্বজ্ঞ।"
    }
  },
  "2:32": {
    "arabic": "قَالُوا سُبْحَانَكَ لَا عِلْمَ لَنَا إِلَّا مَا عَلَّمْتَنَا ۖ إِنَّكَ أَنْتَ الْعَلِيمُ الْحَكِيمُ",
    "meaning": {
      "en": "They said, \"Exalted are You; we have no knowledge except what You have taught us. Indeed, it is You who is the Knowing, the Wise",
      "bn": "তারা বলল, ‘ আপনি পবিত্র মহান ! আপনি আমাদেরকে যা শিক্ষা দিয়েছেন তা ছাড়া আমাদের তো কোনো জ্ঞানই নেই। নিশ্চয় আপনিই সর্বজ্ঞ, প্রজ্ঞাময় ‘।"
    }
  },
  "42:11": {
    "arabic": "فَاطِرُ السَّمَاوَاتِ وَالْأَرْضِ ۚ جَعَلَ لَكُمْ مِنْ أَنْفُسِكُمْ أَزْوَاجًا وَمِنَ الْأَنْعَامِ أَزْوَاجًا ۖ يَذْرَؤُكُمْ فِيهِ ۚ لَيْسَ كَمِثْلِهِ شَيْءٌ ۖ وَهُوَ السَّمِيعُ الْبَصِيرُ",
    "meaning": {
      "en": "[He is] Creator of the heavens and the earth. He has made for you from yourselves, mates, and among the cattle, mates; He multiplies you thereby. There is nothing like unto Him, and He is the Hearing, the Seeing",
      "bn": "তিনি আসমানসমূহ ও যমীনের সৃষ্টিকর্তা, তিনি তোমাদের মধ্য থেকে তোমাদের জোড়া সৃষ্টি করেছেন এবং গৃহপালিত জন্তুর মধ্য থেকে সৃষ্টি করেছেন জোড়া। এভাবে তিনি তোমাদের বংশ বিস্তার করেন; কোনো কিছুই তাঁর সদৃশ নয়, তিনি সর্বশ্রোতা, সর্বদ্ৰষ্টা।"
    }
  },
  "67:14": {
    "arabic": "أَلَا يَعْلَمُ مَنْ خَلَقَ وَهُوَ اللَّطِيفُ الْخَبِيرُ",
    "meaning": {
      "en": "Does He who created not know, while He is the Subtle, the Acquainted",
      "bn": "যিনি সৃষ্টি করেছেন, তিনি কি জানেন না? অথচ তিনি সূক্ষ্মদর্শী, সম্যক অবহিত।"
    }
  },
  "2:225": {
    "arabic": "لَا يُؤَاخِذُكُمُ اللَّهُ بِاللَّغْوِ فِي أَيْمَانِكُمْ وَلَٰكِنْ يُؤَاخِذُكُمْ بِمَا كَسَبَتْ قُلُوبُكُمْ ۗ وَاللَّهُ غَفُورٌ حَلِيمٌ",
    "meaning": {
      "en": "Allah does not impose blame upon you for what is unintentional in your oaths, but He imposes blame upon you for what your hearts have earned. And Allah is Forgiving and Forbearing",
      "bn": "তোমাদের অনর্থক শপথের আল্লাহ্‌ তোমাদেরকে পাকড়াও করবেন না; কিন্তু তিনি সেসব কসমের ব্যাপারে পাকড়াও করবেন, তোমাদের অন্তর যা সংকল্প করে অর্জন করেছে। আর আল্লাহ্‌ ক্ষমাপরায়ণ, পরম সহিষ্ণু।"
    }
  },
  "2:255": {
    "arabic": "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ ۚ لَا تَأْخُذُهُ سِنَةٌ وَلَا نَوْمٌ ۚ لَهُ مَا فِي السَّمَاوَاتِ وَمَا فِي الْأَرْضِ ۗ مَنْ ذَا الَّذِي يَشْفَعُ عِنْدَهُ إِلَّا بِإِذْنِهِ ۚ يَعْلَمُ مَا بَيْنَ أَيْدِيهِمْ وَمَا خَلْفَهُمْ ۖ وَلَا يُحِيطُونَ بِشَيْءٍ مِنْ عِلْمِهِ إِلَّا بِمَا شَاءَ ۚ وَسِعَ كُرْسِيُّهُ السَّمَاوَاتِ وَالْأَرْضَ ۖ وَلَا يَئُودُهُ حِفْظُهُمَا ۚ وَهُوَ الْعَلِيُّ الْعَظِيمُ",
    "meaning": {
      "en": "Allah - there is no deity except Him, the Ever-Living, the Sustainer of [all] existence. Neither drowsiness overtakes Him nor sleep. To Him belongs whatever is in the heavens and whatever is on the earth. Who is it that can intercede with Him except by His permission? He knows what is [presently] before them and what will be after them, and they encompass not a thing of His knowledge except for what He wills. His Kursi extends over the heavens and the earth, and their preservation tires Him not. And He is the Most High, the Most Great",
      "bn": "আল্লাহ্‌, তিনি ছাড়া কোনো সত্য ইলাহ নেই। তিনি চিরঞ্জীব, সর্বসত্তার ধারক। তাঁকে তন্দ্রাও স্পর্শ করতে পারে না, নিদ্রাও নয়। আসমানসমূহে যা রয়েছে ও যমীনে যা রয়েছে সবই তাঁর। কে সে, যে তাঁর অনুমতি ব্যতীত তাঁর কাছে সুপারিশ করবে? তাদের সামনে ও পেছনে যা কিছু আছে তা তিনি জানেন। আর যা তিনি ইচ্ছে করেন তা ছাড়া তাঁর জ্ঞানের কোনো কিছুকেই তারা পরিবেষ্টন করতে পারে না। তাঁর ‘কুরসী’ আসমানসমূহ ও যমীনকে পরিব্যাপ্ত করে আছে; আর এ দুটোর রক্ষণাবেক্ষণ তাঁর জন্য বোঝা হয় না। আর তিনি সুউচ্চ সুমহান।"
    }
  },
  "10:107": {
    "arabic": "وَإِنْ يَمْسَسْكَ اللَّهُ بِضُرٍّ فَلَا كَاشِفَ لَهُ إِلَّا هُوَ ۖ وَإِنْ يُرِدْكَ بِخَيْرٍ فَلَا رَادَّ لِفَضْلِهِ ۚ يُصِيبُ بِهِ مَنْ يَشَاءُ مِنْ عِبَادِهِ ۚ وَهُوَ الْغَفُورُ الرَّحِيمُ",
    "meaning": {
      "en": "And if Allah should touch you with adversity, there is no remover of it except Him; and if He intends for you good, then there is no repeller of His bounty. He causes it to reach whom He wills of His servants. And He is the Forgiving, the Merciful",
      "bn": "‘আর যদি আল্লাহ্‌ আপনাকে কোনো ক্ষতির স্পর্শ করান, তবে তিনি ছাড়া তা মোচনকারী আর কেউ নেই। আর যদি আল্লাহ্‌ আপনার মঙ্গল চান, তবে তাঁর অনুগ্রহ প্রতিহত করার কেউ নেই। তাঁর বান্দাদের মধ্যে যাকে ইচ্ছে তার কাছে সেটা পৌঁছান। আর তিনি পরম ক্ষমাশীল, অতি দয়ালু।‘"
    }
  },
  "64:17": {
    "arabic": "إِنْ تُقْرِضُوا اللَّهَ قَرْضًا حَسَنًا يُضَاعِفْهُ لَكُمْ وَيَغْفِرْ لَكُمْ ۚ وَاللَّهُ شَكُورٌ حَلِيمٌ",
    "meaning": {
      "en": "If you loan Allah a goodly loan, He will multiply it for you and forgive you. And Allah is Most Appreciative and Forbearing",
      "bn": "যদি তোমরা আল্লাহকে উত্তম ঋণ দান কর তিনি তোমাদের জন্য তা বহু গুণ বৃদ্ধি করবেন এবং তিনি তোমাদেরকে ক্ষমা করবেন। আর আল্লাহ গুণগ্ৰাহী, পরম সহিষ্ণু।"
    }
  },
  "13:9": {
    "arabic": "عَالِمُ الْغَيْبِ وَالشَّهَادَةِ الْكَبِيرُ الْمُتَعَالِ",
    "meaning": {
      "en": "[He is] Knower of the unseen and the witnessed, the Grand, the Exalted",
      "bn": "তিনি গায়েব ও প্রকাশ্যের জ্ঞানী, মহান, সর্বোচ্চ।"
    }
  },
  "11:57": {
    "arabic": "فَإِنْ تَوَلَّوْا فَقَدْ أَبْلَغْتُكُمْ مَا أُرْسِلْتُ بِهِ إِلَيْكُمْ ۚ وَيَسْتَخْلِفُ رَبِّي قَوْمًا غَيْرَكُمْ وَلَا تَضُرُّونَهُ شَيْئًا ۚ إِنَّ رَبِّي عَلَىٰ كُلِّ شَيْءٍ حَفِيظٌ",
    "meaning": {
      "en": "But if they turn away, [say], \"I have already conveyed that with which I was sent to you. My Lord will give succession to a people other than you, and you will not harm Him at all. Indeed my Lord is, over all things, Guardian",
      "bn": "‘অতঃপর তোমরা মুখ ফিরিয়ে নিলেও আমি যা সহ তোমাদের কাছে প্রেরিত হয়ছি, আমি তো তা তোমাদের কাছে পৌঁছে দিয়েছি এবং আমার রব তোমাদের থেকে ভিন্ন কোনো সম্প্রদায়কে তোমাদের স্থলাভিষিক্ত করবেন এবং তোমরা তাঁর কোনো ক্ষতি সাধন করতে পারবে না। নিশ্চয় আমার রব সবকিছুর রক্ষণাবেক্ষণকারী।’"
    }
  },
  "4:85": {
    "arabic": "مَنْ يَشْفَعْ شَفَاعَةً حَسَنَةً يَكُنْ لَهُ نَصِيبٌ مِنْهَا ۖ وَمَنْ يَشْفَعْ شَفَاعَةً سَيِّئَةً يَكُنْ لَهُ كِفْلٌ مِنْهَا ۗ وَكَانَ اللَّهُ عَلَىٰ كُلِّ شَيْءٍ مُقِيتًا",
    "meaning": {
      "en": "Whoever intercedes for a good cause will have a reward therefrom; and whoever intercedes for an evil cause will have a burden therefrom. And ever is Allah, over all things, a Keeper",
      "bn": "কেউ কোনো ভালো কাজের সুপারিশ করলে তাতে তার অংশ থাকবে এবং কেউ কোনো মন্দ কাজের সুপারিশ করলে তাতে তার অংশ থাকবে। আর আল্লাহ সব কিছুর উপর নজর রাখেন।"
    }
  },
  "4:86": {
    "arabic": "وَإِذَا حُيِّيتُمْ بِتَحِيَّةٍ فَحَيُّوا بِأَحْسَنَ مِنْهَا أَوْ رُدُّوهَا ۗ إِنَّ اللَّهَ كَانَ عَلَىٰ كُلِّ شَيْءٍ حَسِيبًا",
    "meaning": {
      "en": "And when you are greeted with a greeting, greet [in return] with one better than it or [at least] return it [in a like manner]. Indeed, Allah is ever, over all things, an Accountant",
      "bn": "আর তোমাদেরকে যখন অভিবাদন করা হয় তখন তোমরাও তার চেয়ে উত্তম প্রত্যাভিবাদন করবে অথবা সেটারই অনুরূপ করবে; নিশ্চয়ই আল্লাহ সবকিছুর হিসেব গ্রহণকারী।"
    }
  },
  "82:6": {
    "arabic": "يَا أَيُّهَا الْإِنْسَانُ مَا غَرَّكَ بِرَبِّكَ الْكَرِيمِ",
    "meaning": {
      "en": "O mankind, what has deceived you concerning your Lord, the Generous",
      "bn": "হে মানুষ! কিসে তোমাকে তোমার মহান রব সম্পর্কে বিভ্ৰান্ত করল"
    }
  },
  "4:1": {
    "arabic": "يَا أَيُّهَا النَّاسُ اتَّقُوا رَبَّكُمُ الَّذِي خَلَقَكُمْ مِنْ نَفْسٍ وَاحِدَةٍ وَخَلَقَ مِنْهَا زَوْجَهَا وَبَثَّ مِنْهُمَا رِجَالًا كَثِيرًا وَنِسَاءً ۚ وَاتَّقُوا اللَّهَ الَّذِي تَسَاءَلُونَ بِهِ وَالْأَرْحَامَ ۚ إِنَّ اللَّهَ كَانَ عَلَيْكُمْ رَقِيبًا",
    "meaning": {
      "en": "O mankind, fear your Lord, who created you from one soul and created from it its mate and dispersed from both of them many men and women. And fear Allah, through whom you ask one another, and the wombs. Indeed Allah is ever, over you, an Observer",
      "bn": "হে মানুষ! তোমরা তোমাদের রবের তাকওয়া অবলম্বন কর যিনি তোমাদেরকে এক ব্যক্তি থেকে সৃষ্টি করেছেন ও তার থেকে তার স্ত্রী সৃষ্টি করেছেন এবং তাদের দুজন থেকে বহু নর-নারী ছড়িয়ে দেন; আর তোমরা আল্লাহর তাকওয়া অবলম্বন কর যাঁর নামে তোমরা একে অপরের কাছে নিজ নিজ হক্‌ দাবী কর এবং তাকওয়া অবলম্বন কর রক্ত-সম্পর্কিত আত্মীয়ের ব্যাপারেও। নিশ্চয় আল্লাহ তোমাদের উপর পর্যবেক্ষক।"
    }
  },
  "11:61": {
    "arabic": "۞ وَإِلَىٰ ثَمُودَ أَخَاهُمْ صَالِحًا ۚ قَالَ يَا قَوْمِ اعْبُدُوا اللَّهَ مَا لَكُمْ مِنْ إِلَٰهٍ غَيْرُهُ ۖ هُوَ أَنْشَأَكُمْ مِنَ الْأَرْضِ وَاسْتَعْمَرَكُمْ فِيهَا فَاسْتَغْفِرُوهُ ثُمَّ تُوبُوا إِلَيْهِ ۚ إِنَّ رَبِّي قَرِيبٌ مُجِيبٌ",
    "meaning": {
      "en": "And to Thamud [We sent] their brother Salih. He said, \"O my people, worship Allah; you have no deity other than Him. He has produced you from the earth and settled you in it, so ask forgiveness of Him and then repent to Him. Indeed, my Lord is near and responsive",
      "bn": "আর আমি সামূদ জাতির কাছে তাদের ভাই সালেহকে পাঠিয়েছিলাম। তিনি বলেছিলেন, ‘হে আমার সম্প্রদায়! তোমরা আল্লাহ্‌র ইবাদাত কর, তিনি ছাড়া তোমাদের অন্য কোনো সত্য ইলাহ্ নেই। তিনি তোমাদেরকে মাটি থেকে সৃষ্টি করেছেন এবং তাতেই তিনি তোমাদেরকে বসবাস করিয়েছেন। কাজেই তোমরা তাঁর কাছে ক্ষমা প্রার্থনা কর আর তাঁর দিকেই ফিরে আস। নিশ্চয় আমার রব খুব কাছেই, ডাকে সাড়া প্রদানকারী।‘"
    }
  },
  "2:115": {
    "arabic": "وَلِلَّهِ الْمَشْرِقُ وَالْمَغْرِبُ ۚ فَأَيْنَمَا تُوَلُّوا فَثَمَّ وَجْهُ اللَّهِ ۚ إِنَّ اللَّهَ وَاسِعٌ عَلِيمٌ",
    "meaning": {
      "en": "And to Allah belongs the east and the west. So wherever you [might] turn, there is the Face of Allah. Indeed, Allah is all-Encompassing and Knowing",
      "bn": "আর পূর্ব ও পশ্চিম আল্লাহ্‌রই সুতরাং যেদিকেই তোমরা মুখ ফিরাও না কেন, সেদিকই আল্লাহ্‌র দিক। নিশ্চয়ই আল্লাহ্‌ প্রাচুর্যময়, সর্বজ্ঞ।"
    }
  },
  "85:14": {
    "arabic": "وَهُوَ الْغَفُورُ الْوَدُودُ",
    "meaning": {
      "en": "And He is the Forgiving, the Affectionate",
      "bn": "এবং তিনি ক্ষমাশীল, অতিস্নেহময়"
    }
  },
  "11:73": {
    "arabic": "قَالُوا أَتَعْجَبِينَ مِنْ أَمْرِ اللَّهِ ۖ رَحْمَتُ اللَّهِ وَبَرَكَاتُهُ عَلَيْكُمْ أَهْلَ الْبَيْتِ ۚ إِنَّهُ حَمِيدٌ مَجِيدٌ",
    "meaning": {
      "en": "They said, \"Are you amazed at the decree of Allah? May the mercy of Allah and His blessings be upon you, people of the house. Indeed, He is Praiseworthy and Honorable",
      "bn": "তারা বলল, ‘আল্লাহ্‌র কাজে আপনি বিস্ময় বোধ করছেন? হে নবী পরিবার! আপনাদের প্রতি রয়েছে আল্লাহ্‌র অনুগ্রহ ও কল্যাণ। তিনি তো প্রশংসার যোগ্য ও অত্যন্ত সম্মানিত।"
    }
  },
  "22:17": {
    "arabic": "إِنَّ الَّذِينَ آمَنُوا وَالَّذِينَ هَادُوا وَالصَّابِئِينَ وَالنَّصَارَىٰ وَالْمَجُوسَ وَالَّذِينَ أَشْرَكُوا إِنَّ اللَّهَ يَفْصِلُ بَيْنَهُمْ يَوْمَ الْقِيَامَةِ ۚ إِنَّ اللَّهَ عَلَىٰ كُلِّ شَيْءٍ شَهِيدٌ",
    "meaning": {
      "en": "Indeed, those who have believed and those who were Jews and the Sabeans and the Christians and the Magians and those who associated with Allah - Allah will judge between them on the Day of Resurrection. Indeed Allah is, over all things, Witness",
      "bn": "নিশ্চয় যারা ঈমান এনেছে এবং যারা ইয়াহূদী হয়েছে, যারা সাবিয়ী, নাসারা ও অগ্নিপূজক এবং যারা শিরক করেছে কেয়ামতের দিন আল্লাহ্ তাদের মধ্যে ফয়সালা করে দেবেন। নিশ্চয় আল্লাহ্ সব কিছুর সম্যক প্রত্যক্ষকারী।"
    }
  },
  "22:6": {
    "arabic": "ذَٰلِكَ بِأَنَّ اللَّهَ هُوَ الْحَقُّ وَأَنَّهُ يُحْيِي الْمَوْتَىٰ وَأَنَّهُ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    "meaning": {
      "en": "That is because Allah is the Truth and because He gives life to the dead and because He is over all things competent",
      "bn": "এটা এ জন্য যে, আল্লাহই সত্য এবং তিনিই মৃতকে জীবিত করেন এবং তিনি সব কিছুর উপর ক্ষমতাবান"
    }
  },
  "3:173": {
    "arabic": "الَّذِينَ قَالَ لَهُمُ النَّاسُ إِنَّ النَّاسَ قَدْ جَمَعُوا لَكُمْ فَاخْشَوْهُمْ فَزَادَهُمْ إِيمَانًا وَقَالُوا حَسْبُنَا اللَّهُ وَنِعْمَ الْوَكِيلُ",
    "meaning": {
      "en": "Those to whom hypocrites said, \"Indeed, the people have gathered against you, so fear them.\" But it [merely] increased them in faith, and they said, \"Sufficient for us is Allah, and [He is] the best Disposer of affairs",
      "bn": "এদেরকে লোকেরা বলেছিল, তোমাদের বিরুদ্ধে লোক জড়ো হয়েছে, কাজেই তোমরা তাদেরকে ভয় কর; কিন্তু এ কথা তাদের ঈমানকে আরো বাড়িয়ে দিয়েছিল এবং তারা বলেছিল, ‘আল্লাহ্‌ই আমাদের জন্য যথেষ্ট এবং তিনি কত উত্তম কর্মবিধায়ক’"
    }
  },
  "42:19": {
    "arabic": "اللَّهُ لَطِيفٌ بِعِبَادِهِ يَرْزُقُ مَنْ يَشَاءُ ۖ وَهُوَ الْقَوِيُّ الْعَزِيزُ",
    "meaning": {
      "en": "Allah is Subtle with His servants; He gives provisions to whom He wills. And He is the Powerful, the Exalted in Might",
      "bn": "আল্লাহ্ তাঁর বান্দাদের প্রতি অত্যন্ত কোমল; তিনি যাকে ইচ্ছে রিযিক দান করেন। আর তিনি সর্বশক্তিমান, প্ৰবল পরাক্রমশালী।"
    }
  },
  "42:28": {
    "arabic": "وَهُوَ الَّذِي يُنَزِّلُ الْغَيْثَ مِنْ بَعْدِ مَا قَنَطُوا وَيَنْشُرُ رَحْمَتَهُ ۚ وَهُوَ الْوَلِيُّ الْحَمِيدُ",
    "meaning": {
      "en": "And it is He who sends down the rain after they had despaired and spreads His mercy. And He is the Protector, the Praiseworthy",
      "bn": "আর তাদের নিরাশ হওয়ার পরে তিনিই বৃষ্টি প্রেরণ করেন এবং তাঁর রহমত ছড়িয়ে দেন এবং তিনিই অভিভাবক, অত্যন্ত প্ৰশংসিত।"
    }
  },
  "31:26": {
    "arabic": "لِلَّهِ مَا فِي السَّمَاوَاتِ وَالْأَرْضِ ۚ إِنَّ اللَّهَ هُوَ الْغَنِيُّ الْحَمِيدُ",
    "meaning": {
      "en": "To Allah belongs whatever is in the heavens and earth. Indeed, Allah is the Free of need, the Praiseworthy",
      "bn": "আসমানসমূহ ও যমীনে যা কিছু আছে তা আল্লাহরই; নিশ্চয় আল্লাহ্, তিনি তো অভাবমুক্ত, চির প্রশংসিত।"
    }
  },
  "30:50": {
    "arabic": "فَانْظُرْ إِلَىٰ آثَارِ رَحْمَتِ اللَّهِ كَيْفَ يُحْيِي الْأَرْضَ بَعْدَ مَوْتِهَا ۚ إِنَّ ذَٰلِكَ لَمُحْيِي الْمَوْتَىٰ ۖ وَهُوَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    "meaning": {
      "en": "So observe the effects of the mercy of Allah - how He gives life to the earth after its lifelessness. Indeed, that [same one] will give life to the dead, and He is over all things competent",
      "bn": "সুতরাং আপনি আল্লাহ্‌র অনুগ্রহের ফল সম্বন্ধে চিন্তা করুন, কিভাবে তিনি যমীনকে জীবিত করেন সেটার মৃত্যুর পর। এভাবেই তো আল্লাহ্ মৃতকে জীবিতকারী আর তিনি সবকিছুর উপর ক্ষমতাবান।"
    }
  },
  "112:1": {
    "arabic": "قُلْ هُوَ اللَّهُ أَحَدٌ",
    "meaning": {
      "en": "Say, \"He is Allah, [who is] One",
      "bn": "বলুন, ‘তিনি আল্লাহ্, এক-অদ্বিতীয়"
    }
  },
  "112:2": {
    "arabic": "اللَّهُ الصَّمَدُ",
    "meaning": {
      "en": "Allah, the Eternal Refuge",
      "bn": "‘আল্লাহ্ হচ্ছেন ‘সামাদ' (তিনি কারো মুখাপেক্ষী নন, সকলেই তাঁর মুখাপেক্ষী)"
    }
  },
  "6:65": {
    "arabic": "قُلْ هُوَ الْقَادِرُ عَلَىٰ أَنْ يَبْعَثَ عَلَيْكُمْ عَذَابًا مِنْ فَوْقِكُمْ أَوْ مِنْ تَحْتِ أَرْجُلِكُمْ أَوْ يَلْبِسَكُمْ شِيَعًا وَيُذِيقَ بَعْضَكُمْ بَأْسَ بَعْضٍ ۗ انْظُرْ كَيْفَ نُصَرِّفُ الْآيَاتِ لَعَلَّهُمْ يَفْقَهُونَ",
    "meaning": {
      "en": "Say, \"He is the [one] Able to send upon you affliction from above you or from beneath your feet or to confuse you [so you become] sects and make you taste the violence of one another.\" Look how We diversify the signs that they might understand",
      "bn": "বলুন, ‘তোমাদের উপর বা নীচ থেকে শাস্তি পাঠাতে,বা তোমাদেরকে বিভিন্ন সন্দেহপূর্ণ দলে বিভক্ত করতে বা এক দলকে অন্য দলের সংঘর্ষের আস্বাদ গ্রহণ করাতে তিনি (আল্লাহ) সক্ষম।’ দেখুন,আমারা কি রূপে বিভিন্নভাবে আয়াতসদমূহ বিবৃত করি যাতে তারা ভালোভাবে বুঝতে পারে।"
    }
  },
  "54:55": {
    "arabic": "فِي مَقْعَدِ صِدْقٍ عِنْدَ مَلِيكٍ مُقْتَدِرٍ",
    "meaning": {
      "en": "In a seat of honor near a Sovereign, Perfect in Ability",
      "bn": "যথাযোগ্য আসনে, সর্বশক্তিমান মহাঅধিপতি (আল্লাহ্‌)র সান্নিধ্যে।"
    }
  },
  "57:3": {
    "arabic": "هُوَ الْأَوَّلُ وَالْآخِرُ وَالظَّاهِرُ وَالْبَاطِنُ ۖ وَهُوَ بِكُلِّ شَيْءٍ عَلِيمٌ",
    "meaning": {
      "en": "He is the First and the Last, the Ascendant and the Intimate, and He is, of all things, Knowing",
      "bn": "তিনিই প্রথম ও শেষ; প্রকাশ্য (উপরে) ও গোপন (নিকটে) আর তিনি সবকিছু সম্পর্কে সম্যক অবগত।"
    }
  },
  "52:28": {
    "arabic": "إِنَّا كُنَّا مِنْ قَبْلُ نَدْعُوهُ ۖ إِنَّهُ هُوَ الْبَرُّ الرَّحِيمُ",
    "meaning": {
      "en": "Indeed, we used to supplicate Him before. Indeed, it is He who is the Beneficent, the Merciful",
      "bn": "নিশ্চয় আমরা আগেও আল্লাহকে ডাকতাম, নিশ্চয় তিনি কৃপাময়, পরম দয়ালু।"
    }
  },
  "2:37": {
    "arabic": "فَتَلَقَّىٰ آدَمُ مِنْ رَبِّهِ كَلِمَاتٍ فَتَابَ عَلَيْهِ ۚ إِنَّهُ هُوَ التَّوَّابُ الرَّحِيمُ",
    "meaning": {
      "en": "Then Adam received from his Lord [some] words, and He accepted his repentance. Indeed, it is He who is the Accepting of repentance, the Merciful",
      "bn": "তারপর আদম তার রবের কাছ থেকে কিছু বাণী পেলেন। অতঃপর আল্লাহ্‌ তার তাওবা কবুল করলেন। নিশ্চয় তিনিই তাওবা কবুলকারী, পরম দয়ালু।"
    }
  },
  "4:43": {
    "arabic": "يَا أَيُّهَا الَّذِينَ آمَنُوا لَا تَقْرَبُوا الصَّلَاةَ وَأَنْتُمْ سُكَارَىٰ حَتَّىٰ تَعْلَمُوا مَا تَقُولُونَ وَلَا جُنُبًا إِلَّا عَابِرِي سَبِيلٍ حَتَّىٰ تَغْتَسِلُوا ۚ وَإِنْ كُنْتُمْ مَرْضَىٰ أَوْ عَلَىٰ سَفَرٍ أَوْ جَاءَ أَحَدٌ مِنْكُمْ مِنَ الْغَائِطِ أَوْ لَامَسْتُمُ النِّسَاءَ فَلَمْ تَجِدُوا مَاءً فَتَيَمَّمُوا صَعِيدًا طَيِّبًا فَامْسَحُوا بِوُجُوهِكُمْ وَأَيْدِيكُمْ ۗ إِنَّ اللَّهَ كَانَ عَفُوًّا غَفُورًا",
    "meaning": {
      "en": "O you who have believed, do not approach prayer while you are intoxicated until you know what you are saying or in a state of janabah, except those passing through [a place of prayer], until you have washed [your whole body]. And if you are ill or on a journey or one of you comes from the place of relieving himself or you have contacted women and find no water, then seek clean earth and wipe over your faces and your hands [with it]. Indeed, Allah is ever Pardoning and Forgiving",
      "bn": "হে মুমিনগণ! নেশাগ্রস্ত অবস্থায় তোমরা সালাতের নিকটবর্তী হয়ো না, যতক্ষণ না তোমরা যা বল তা বুঝতে পার এবং যদি তোমরা মুসাফির না হও তবে অপবিত্র অবস্থাতেও নয়, যতক্ষণ পর্যন্ত না তোমরা গোসল কর। আর যদি তোমরা পীড়িত হও অথবা সফরে থাক বা তোমাদের কেউ শৌচস্থান থেকে আসে অথবা তোমরা নারী সম্ভোগ কর এবং পানি না পাও তবে পবিত্র মাটির দ্বারা তায়াম্মুম কর। সুতরাং মাসেহ কর তোমরা তোমাদের চেহারা ও হাত, নিশ্চয় আল্লাহ পাপ মোচনকারী, ক্ষমাশীল।"
    }
  },
  "2:143": {
    "arabic": "وَكَذَٰلِكَ جَعَلْنَاكُمْ أُمَّةً وَسَطًا لِتَكُونُوا شُهَدَاءَ عَلَى النَّاسِ وَيَكُونَ الرَّسُولُ عَلَيْكُمْ شَهِيدًا ۗ وَمَا جَعَلْنَا الْقِبْلَةَ الَّتِي كُنْتَ عَلَيْهَا إِلَّا لِنَعْلَمَ مَنْ يَتَّبِعُ الرَّسُولَ مِمَّنْ يَنْقَلِبُ عَلَىٰ عَقِبَيْهِ ۚ وَإِنْ كَانَتْ لَكَبِيرَةً إِلَّا عَلَى الَّذِينَ هَدَى اللَّهُ ۗ وَمَا كَانَ اللَّهُ لِيُضِيعَ إِيمَانَكُمْ ۚ إِنَّ اللَّهَ بِالنَّاسِ لَرَءُوفٌ رَحِيمٌ",
    "meaning": {
      "en": "And thus we have made you a just community that you will be witnesses over the people and the Messenger will be a witness over you. And We did not make the qiblah which you used to face except that We might make evident who would follow the Messenger from who would turn back on his heels. And indeed, it is difficult except for those whom Allah has guided. And never would Allah have caused you to lose your faith. Indeed Allah is, to the people, Kind and Merciful",
      "bn": "আর এভাবে আমরা তোমাদেরকে এক মধ্যপন্থী জাতিতে পরিণত করেছি, যাতে তোমরা মানবজাতির উপর স্বাক্ষী হও এবং রাসূল তোমাদের উপর সাক্ষী হতে পারেন আর আপনি এ যাবত যে কিবলা অনুসরণ করছিলেন সেটাকে আমরা এ উদ্দেশ্যে কেবলায় পরিণত করেছিলাম যাতে প্রকাশ করে দিতে পারি কে রাসূলের অনুসরণ করে এবং কে পিছনে ফিরে যায় ? আল্লাহ্‌ যাদেরকে হিদায়াত করেছেন তারা ছাড়া অন্যদের উপর এটা নিশ্চিত কঠিন। আল্লাহ্‌ এরূপ নন যে, তোমাদের ঈমানকে ব্যর্থ করে দিবেন। নিশ্চয় আল্লাহ্‌ মানুষের প্রতি সহানুভূতিশীল, পরম দয়ালু।"
    }
  },
  "3:26": {
    "arabic": "قُلِ اللَّهُمَّ مَالِكَ الْمُلْكِ تُؤْتِي الْمُلْكَ مَنْ تَشَاءُ وَتَنْزِعُ الْمُلْكَ مِمَّنْ تَشَاءُ وَتُعِزُّ مَنْ تَشَاءُ وَتُذِلُّ مَنْ تَشَاءُ ۖ بِيَدِكَ الْخَيْرُ ۖ إِنَّكَ عَلَىٰ كُلِّ شَيْءٍ قَدِيرٌ",
    "meaning": {
      "en": "Say, \"O Allah, Owner of Sovereignty, You give sovereignty to whom You will and You take sovereignty away from whom You will. You honor whom You will and You humble whom You will. In Your hand is [all] good. Indeed, You are over all things competent",
      "bn": "বলুন, ‘হে সার্বভৌম শক্তির মালিক আল্লাহ্‌! আপনি যাকে ইচ্ছা ক্ষমতা প্রদান করেন এবং যার থেকে ইচ্ছা ক্ষমতা কেড়ে নেন; যাকে ইচ্ছা আপনি সম্মানিত করেন আর যাকে ইচ্ছা আপনি হীন করেন। কল্যান আপনারই হাতে। নিশ্চয়ই আপনি সবকিছুর উপর ক্ষমতাবান।"
    }
  },
  "55:27": {
    "arabic": "وَيَبْقَىٰ وَجْهُ رَبِّكَ ذُو الْجَلَالِ وَالْإِكْرَامِ",
    "meaning": {
      "en": "And there will remain the Face of your Lord, Owner of Majesty and Honor",
      "bn": "আর অবিনশ্বর শুধু আপনার রবের চেহারা, যিনি মহিমাময়, মহানুভব"
    }
  },
  "3:9": {
    "arabic": "رَبَّنَا إِنَّكَ جَامِعُ النَّاسِ لِيَوْمٍ لَا رَيْبَ فِيهِ ۚ إِنَّ اللَّهَ لَا يُخْلِفُ الْمِيعَادَ",
    "meaning": {
      "en": "Our Lord, surely You will gather the people for a Day about which there is no doubt. Indeed, Allah does not fail in His promise",
      "bn": "‘হে আমাদের রব! নিশ্চয় আপনি সমস্ত মানুষকে একদিন একত্রে সমবেত করবেন এতে কোনো সন্দেহ নেই; নিশ্চয় আল্লাহ্‌ ওয়াদা খেলাফ করেন না।’"
    }
  },
  "35:15": {
    "arabic": "۞ يَا أَيُّهَا النَّاسُ أَنْتُمُ الْفُقَرَاءُ إِلَى اللَّهِ ۖ وَاللَّهُ هُوَ الْغَنِيُّ الْحَمِيدُ",
    "meaning": {
      "en": "O mankind, you are those in need of Allah, while Allah is the Free of need, the Praiseworthy",
      "bn": "হে মানুষ! তোমরা আল্লাহর মুখাপেক্ষী; আর আল্লাহ্, তিনিই অভাবমুক্ত, প্রশংসিত।"
    }
  },
  "24:35": {
    "arabic": "۞ اللَّهُ نُورُ السَّمَاوَاتِ وَالْأَرْضِ ۚ مَثَلُ نُورِهِ كَمِشْكَاةٍ فِيهَا مِصْبَاحٌ ۖ الْمِصْبَاحُ فِي زُجَاجَةٍ ۖ الزُّجَاجَةُ كَأَنَّهَا كَوْكَبٌ دُرِّيٌّ يُوقَدُ مِنْ شَجَرَةٍ مُبَارَكَةٍ زَيْتُونَةٍ لَا شَرْقِيَّةٍ وَلَا غَرْبِيَّةٍ يَكَادُ زَيْتُهَا يُضِيءُ وَلَوْ لَمْ تَمْسَسْهُ نَارٌ ۚ نُورٌ عَلَىٰ نُورٍ ۗ يَهْدِي اللَّهُ لِنُورِهِ مَنْ يَشَاءُ ۚ وَيَضْرِبُ اللَّهُ الْأَمْثَالَ لِلنَّاسِ ۗ وَاللَّهُ بِكُلِّ شَيْءٍ عَلِيمٌ",
    "meaning": {
      "en": "Allah is the Light of the heavens and the earth. The example of His light is like a niche within which is a lamp, the lamp is within glass, the glass as if it were a pearly [white] star lit from [the oil of] a blessed olive tree, neither of the east nor of the west, whose oil would almost glow even if untouched by fire. Light upon light. Allah guides to His light whom He wills. And Allah presents examples for the people, and Allah is Knowing of all things",
      "bn": "আল্লাহ্‌ আসমানসমূহ ও যমীনের নূর, তাঁর নূরের উপমা যেন একটি দীপাধার যার মধ্যে আছে এক প্রদীপ, প্রদীপটি একটি কাঁচের আবরণের মধ্যে স্থাপিত, কাঁচের আবরণটি উজ্জ্বল নক্ষত্রের মত, তা জ্বালানো হয় বরকতময় যায়তূন গাছের তৈল দ্বারা যা শুধু পূর্ব দিকের (সূর্যের আলোকপ্রাপ্ত) নয় আবার শুধু পশ্চিম দিকের (সূর্যের আলোকপ্রাপ্তও) নয়, আগুন তাকে স্পর্শ না করলেও যেন তার তৈল উজ্জ্বল আলো দিচ্ছে; নূরের উপর নূর! আল্লাহ্‌ যাকে ইচ্ছে হেদায়েত করেন তাঁর নূরের দিকে। আল্লাহ্‌ মানুষের জন্য উপমাসমূহ বর্ণনা করে থাকেন এবং আল্লাহ্‌ সব কিছু সম্পর্কে সর্বজ্ঞ।"
    }
  },
  "25:31": {
    "arabic": "وَكَذَٰلِكَ جَعَلْنَا لِكُلِّ نَبِيٍّ عَدُوًّا مِنَ الْمُجْرِمِينَ ۗ وَكَفَىٰ بِرَبِّكَ هَادِيًا وَنَصِيرًا",
    "meaning": {
      "en": "And thus have We made for every prophet an enemy from among the criminals. But sufficient is your Lord as a guide and a helper",
      "bn": "আল্লাহ্‌ বলেন, ‘আর এভাবেই আমরা প্রত্যেক নবীর জন্য অপরাধীদের থেকে শত্রু বানিয়ে থাকি। আর আপনার রবই পথপ্রদর্শক ও সাহায্যকারীরূপে যথেষ্ট।’"
    }
  },
  "2:117": {
    "arabic": "بَدِيعُ السَّمَاوَاتِ وَالْأَرْضِ ۖ وَإِذَا قَضَىٰ أَمْرًا فَإِنَّمَا يَقُولُ لَهُ كُنْ فَيَكُونُ",
    "meaning": {
      "en": "Originator of the heavens and the earth. When He decrees a matter, He only says to it, \"Be,\" and it is",
      "bn": "তিনি আসমানসমূহ ও যমীনের উদ্ভাবক। আর যখন তিনি কোনো কিছু করার সিদ্ধান্ত নেন, তখন তার জন্য শুধু বলেন, ‘হও’, ফলে তা হয়ে যায়।"
    }
  }
};

export const NAME_HIGHLIGHT: Record<string, [number, number]> = {"asma_001":[13,13],"asma_002":[14,14],"asma_003":[7,7],"asma_004":[8,8],"asma_005":[9,9],"asma_006":[10,10],"asma_007":[11,11],"asma_008":[12,12],"asma_009":[13,13],"asma_010":[14,14],"asma_011":[2,2],"asma_012":[3,3],"asma_013":[4,4],"asma_014":[6,6],"asma_015":[48,48],"asma_016":[15,15],"asma_017":[3,3],"asma_018":[9,9],"asma_019":[11,11],"asma_026":[21,21],"asma_027":[22,22],"asma_030":[5,5],"asma_031":[6,6],"asma_032":[14,14],"asma_033":[57,57],"asma_034":[25,25],"asma_035":[11,11],"asma_036":[56,56],"asma_037":[3,3],"asma_038":[22,22],"asma_039":[23,23],"asma_040":[15,15],"asma_042":[6,6],"asma_043":[30,30],"asma_044":[31,31],"asma_045":[12,12],"asma_046":[12,12],"asma_047":[2,2],"asma_048":[15,15],"asma_050":[22,22],"asma_051":[4,4],"asma_052":[16,16],"asma_053":[8,8],"asma_054":[6,6],"asma_055":[12,12],"asma_056":[10,10],"asma_060":[13,13],"asma_062":[5,5],"asma_063":[6,6],"asma_066":[47,47],"asma_067":[3,3],"asma_068":[1,1],"asma_069":[2,2],"asma_070":[5,5],"asma_073":[1,1],"asma_074":[2,2],"asma_075":[3,3],"asma_076":[4,4],"asma_078":[4,4],"asma_079":[8,8],"asma_080":[10,10],"asma_082":[49,49],"asma_083":[47,47],"asma_084":[2,3],"asma_085":[3,5],"asma_087":[2,2],"asma_088":[11,11],"asma_093":[2,2],"asma_094":[10,10],"asma_095":[0,0]};
